<?php

return [
    'additional_city_price_cop' => 9900,
    'promotions' => [
        'city_featured_weekly_cop' => 19900,
        'home_featured_weekly_cop' => 39900,
    ],
    'plans' => [
        'basic' => [
            'name' => 'Plan Basico',
            'price_cop' => 29900,
            'listing_limit' => 1,
            'included_cities' => 1,
            'max_photos_per_listing' => 5,
            'max_videos_per_listing' => 0,
            'show_whatsapp' => false,
            'show_phone' => false,
            'priority_level' => 10,
            'allows_verification' => false,
            'allows_featured_city' => false,
            'allows_featured_home' => false,
            'has_premium_badge' => false,
            'has_advanced_stats' => false,
            'sort_order' => 10,
        ],
        'pro' => [
            'name' => 'Plan Pro',
            'price_cop' => 59900,
            'listing_limit' => 3,
            'included_cities' => 3,
            'max_photos_per_listing' => 10,
            'max_videos_per_listing' => 1,
            'show_whatsapp' => true,
            'show_phone' => true,
            'priority_level' => 30,
            'allows_verification' => true,
            'allows_featured_city' => false,
            'allows_featured_home' => false,
            'has_premium_badge' => false,
            'has_advanced_stats' => true,
            'sort_order' => 20,
        ],
        'premium' => [
            'name' => 'Plan Premium',
            'price_cop' => 99900,
            'listing_limit' => 6,
            'included_cities' => 6,
            'max_photos_per_listing' => 20,
            'max_videos_per_listing' => 3,
            'show_whatsapp' => true,
            'show_phone' => true,
            'priority_level' => 60,
            'allows_verification' => true,
            'allows_featured_city' => true,
            'allows_featured_home' => true,
            'has_premium_badge' => true,
            'has_advanced_stats' => true,
            'sort_order' => 30,
        ],
    ],
];
